// SPDX-License-Identifier: MIT

#pragma once

#include <cstddef>
#include <string_view>

namespace securepath::log {

/**
 *	\brief Contains info where log macro (log.hpp) was called with specific log level
 */
struct log_info {
	char const* file;
	std::size_t line;
	int level;
};

/**
 *  \bried formatted_message is generated by default_logger and used by outputs via basic_backend to log messages
 *	\param info contains file, line and level of the log message
 *	\param message contains log message 
 */
struct formatted_message {
	log_info const& info;
	std::string_view message;
	std::string_view category;
};

}

